### PR TITLE
Fix crash when rack.input buffer is missing pos method

### LINKED ISSUE #122: Logs littered with undefined method `pos' for #<Unicorn::TeeInput:0x000000158d8398>
Every some seconds.

https://github.com/MindscapeHQ/raygun4ruby/blob/master/lib/raygun/client.rb#L144

```
F, [2017-08-28T06:46:33.634868 #2092] FATAL -- : Exception Class: NoMethodError
Exception message: undefined method `pos' for #<Unicorn::TeeInput:0x000000158d8398>

===================================================================
Backtrace:
===================================================================

  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:144:in `raw_data'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:102:in `request_information'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:194:in `build_payload_hash'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/client.rb:26:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:123:in `track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:61:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:137:in `rescue in track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:121:in `track_exception_sync'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun.rb:61:in `track_exception'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/middleware/rack_exception_interceptor.rb:12:in `rescue in call'
  /home/deploy/apps/vydia/shared/bundle/ruby/2.1.0/gems/raygun4ruby-2.3.0/lib/raygun/middleware/rack_exception_interceptor.rb:10:in `call'
```

### PR DESCRIPTION
**Pull request by UberMouse**
Resolves #122

### CODE REVIEW

File: lib/raygun/client.rb [hunk 1]
```diff
@@ -140,7 +140,7 @@ def raw_data(rack_env)
 
         # If size is 0 the buffer is at best empty and at worst
         # something like the Puma::NullIO buffer which is missing methods
-        if input && input.size && !request.form_data?
+        if input && input.size && input.respond_to?(:pos) && !request.form_data?
```
Comment (TSMMark) [inline lib/raygun/client.rb]: is there a way we could still receive the input data in the raygun tracking instead of skipping it?

Comment (UberMouse) [reply lib/raygun/client.rb]: There's probably a way to make it work with the Unicorn buffer, but so far the `raw_data` method has been the most problematic one in the client so I really need to do another investigation and try to figure out a more reliable method of reading the raw request data. One that works across the various web servers.

Unfortunately, I'm a bit swamped with work currently so it will probably be a few weeks before I have time to look. If it's important I can talk to my manager about getting some work shuffled around to bump this up.

Did you just recently update to a newer version of Raygun4Ruby? I did some work a few months ago to make the raw_data method more reliable to fix an issue reported, but it's possible that broke it for your setup on Unicorn (or just unicorn in general).

Comment (TSMMark) [reply lib/raygun/client.rb]: No recent upgrade. I think the only reason we noticed is that we happened to start getting a slew of webhook requests that were erroring, and raygun4ruby was choking on the buffer, causing our logs to blow up.

It's unfortunate we won't be able to get this working with our Unicorn setup as I believe we were one of the original raygun customers that requested this feature in the first place 😆

Comment (UberMouse) [reply lib/raygun/client.rb]: Not the best solution :( I've had a talk with my manager but unfortunately, I probably won't be able to get any time to work on this until next week at the earliest, but probably not until the week after that. Would have time to look at a PR if one got sent my way before that, but otherwise, it will be a few weeks I'm afraid.

Was it reading the raw data before and it just started blowing up or has that been an issue for a while?

Comment (TSMMark) [reply lib/raygun/client.rb]: My team is telling me it works/worked for some requests but does not for others. Sorry, I don't have more information right now.

Comment (TSMMark) [reply lib/raygun/client.rb]: Definitely still looking forward to this!

Comment (UberMouse) [reply lib/raygun/client.rb]: Hey @TSMMark, I've just pushed Raygun4Ruby v2.5.0 to RubyGems with better handling for raw_datamm. Should not break in this case and let you capture the raw_data again. Sorry it's taken so long!

Comment (TSMMark) [reply lib/raygun/client.rb]: Thanks! Updating version now
